version: "3.8"

services:
  database:
    image: mongo:5.0
    restart: unless-stopped
    container_name: trading-sandbox-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASSWORD}
    ports:
      - ${MONGOPORT}:27017
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:27017" ]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis
    restart: unless-stopped
    container_name: trading-sandbox-redis
    ports:
      - ${REDISPORT}:6379
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6379" ]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: trading-sandbox-api
    environment:
      - MONGOHOST=database
      - MONGOPORT=27017
      - REDISHOST=redis
      - REDISPORT=6379
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - database
      - redis
