version: "3.8"

services:
  database:
    image: mongo:5.0
    restart: unless-stopped
    container_name: trading-sandbox-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:27017" ]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis
    restart: unless-stopped
    container_name: trading-sandbox-redis
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6379" ]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: trading-sandbox-api
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - database
      - redis
